name: Create Deployment PR
permissions: write-all
on: workflow_dispatch

jobs:
  deploy:
    name: Create Deployment PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
      # Prepare staging branch to point to HEAD of main.

      # Delete staging branch if it already exists.
      - name: Delete staging branch if exists
        run: git branch -D staging
        continue-on-error: true
      # Then recreate from main.
      - name: Create new staging branch from main
        run: git checkout -b "staging"
      - name: Fetch production branch
        run: git fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/production*:refs/remotes/origin/production*
      - name: Merge production
        run: git merge origin/production --ff -m "Merge branch 'production' into staging"
      - name: Force push changes
        run: git push --force --set-upstream origin staging

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "staging"
          destination_branch: "production"
          pr_title: "Deploy to Production"
          pr_body: |
            ###  Deploy to Production
          pr_label: "deployment"
          pr_draft: false
          pr_allow_empty: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
