name: "deploy-check"
on: [push]

jobs:
  deply_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: hmarr/debug-action@v2
    - uses: LouisBrunner/checks-action@v1.1.1
      if: always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Test XYZ
        conclusion: ${{ job.status }}