name: Deployment
on:
  pull_request:
    types:
      - labeled
      - unlabeled
    branches:    
      - production
jobs:
  require-label:
    name: Require "merge deployment" label
    runs-on: ubuntu-latest
    if: |-
      ${{ 
        github.event.label.name == 'merge deployment' &&
        github.event.pull_request.state == 'open'
      }}
    steps:
      - uses: hmarr/debug-action@v2
      - uses: mheap/github-action-required-labels@v1
        with:
          mode: exactly
          count: 1
          labels: merge deployment
