name: "deploy-check"
on:
  pull_request:
    branches:    
      - 'production'
permissions: write-all

jobs:
  deply_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hmarr/debug-action@v2
    - run: "curl -H 'Accept: application/vnd.github.v3+json' 'https://api.github.com/repos/cvle/nextjs2/commits/staging/check-runs?check_name=Merge%20PR'"
      id: checks
    - run: echo ${{ steps.checks.outputs.total_count }}