name: Deploy Automerge Label
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
    branches:    
      - 'production'
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v1
        with:
          mode: exactly
          count: 1
          labels: "automerge"