name: "deploy-check"
on:
  push:
    branches:    
      - 'staging'
permissions: write-all

jobs:
  deploy_label_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hmarr/debug-action@v2
    - uses: LouisBrunner/checks-action@v1.2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Wait for Merge Label
        status: in_progress