name: Deployment
permissions: write-all
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:    
      - production
jobs:
  create-check:
    name: Create Check
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'merge deployment') }}
    steps:
      - uses: LouisBrunner/checks-action@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Wait for label
          status: in_progress
