name: Deployment
permissions:
  contents: write
on:
  pull_request:
    types:
      - labeled
    branches:    
      - production
jobs:
  merge:
    name: Merge
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'merge deployment') }}
    steps:
      # Uses .mergepal.yml for additional configurations.
      - uses: maxkomarychev/merge-pal-action@v0.5.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions-ecosystem/action-remove-labels@v1
        if: failure()
        with:
          labels: merge deployment
