name: Deployment
permissions: write-all
on:
  pull_request:
    types:
      - labeled
      - unlabeled
    branches:    
      - production
jobs:
  create-check:
    name: Require "merge deployment" label
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v1
        with:
          mode: exactly
          count: 1
          labels: merge deployment
