name: Deployment
permissions: write-all
on:
  pull_request:
    types:
      - labeled
    branches:    
      - production
jobs:
  merge:
    name: Merge
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'merge deployment') }}
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.15.3"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: merge deployment
          MERGE_METHOD: merge
          MERGE_DELETE_BRANCH: false
          MERGE_ERROR_FAIL: true
          UPDATE_LABELS: disable
      - uses: actions-ecosystem/action-remove-labels@v1
        if: failure()
        with:
          labels: merge deployment
