name: Deployment
permissions: write-all
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:    
      - production
jobs:
  create-check:
    name: Create merge label check
    runs-on: ubuntu-latest
    steps:
      - uses: LouisBrunner/checks-action@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Wait for merge label
          status: in_progress
        continue-on-error: true
