name: Deployment
permissions:
  contents: write
on:
  pull_request:
    types:
      - labeled
    branches:    
      - production
jobs:
  merge:
    name: Merge
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'merge deployment') }}
    steps:
      - uses: hmarr/debug-action@v2
      - uses: actions/setup-node@v3
      - run: >
          npx is-mergeable 
          --owner $GITHUB_REPOSITORY_OWNER
          --repo ${{ github.event.pull_request.base.repo.name }}
          --pull-request ${{ github.event.number }}
          --min-reviews 1
          --check 'Require "merge deployment" label'
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions-ecosystem/action-remove-labels@v1
        if: failure()
        with:
          labels: merge deployment
