name: automerge
permissions: write-all
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - reopened
      - unlocked
    branches:    
      - production
  pull_request_review:
    types:
      - submitted
    branches:    
      - production
  check_suite:
    types:
      - completed
    branches:    
      - staging
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'automerge') }}
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: automerge
          MERGE_METHOD: merge
          MERGE_DELETE_BRANCH: false
          MERGE_ERROR_FAIL: true
